version: "3"
services:
  proxy:
    image: lucky-proxy
    build:
      context: ../../services/proxy
      dockerfile: Dockerfile
    container_name: lucky_proxy
    hostname: lucky-proxy
    depends_on:
      - frontend
      - movie
      - music
    ports:
      - "800:80"
    volumes:
      - ../../services/proxy/config/nginx.conf:/etc/nginx/nginx.conf
      - ../../services/proxy/config/default.conf:/etc/nginx/conf.d/default.conf

  frontend:
    image: lucky-frontend
    build:
      context: ../../services/frontend
      dockerfile: Dockerfile
    restart: always
    container_name: lucky_frontend
    hostname: lucky-frontend
    ports:
      - "801:80"
    volumes:
      - ../../services/frontend/app:/app
      - ../../services/frontend/app/src:/usr/share/nginx/html
      - ../../services/frontend/config/nginx.conf:/etc/nginx/nginx.conf
      - ../../services/frontend/config/default.conf:/etc/nginx/conf.d/default.conf

  movie:
    image: lucky-movie
    build:
      context: ../../services/backend/movie
      dockerfile: Dockerfile
      args:
        - PORT=80
        - FLASK_DEBUG=False
    restart: always
    container_name: lucky_api_movie
    hostname: lucky-api-movie
    ports:
      - "802:80"
    volumes:
      - ../../services/backend/movie/app:/app

  music:
    image: lucky-music
    build:
      context: ../../services/backend/music
      dockerfile: docker/Dockerfile.prod
      args:
        - PORT=80
        - ASPNETCORE_ENVIRONMENT=Production
    restart: always
    container_name: lucky_api_music
    hostname: lucky-api-music
    ports:
      - "803:80"
